# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.static import serve
from django.conf import  settings
from controler.views import *


urlpatterns = [
    ##url(r'^admin/', admin.site.urls),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}, name = 'static'),
    url(r'^$',login),
    url(r'^login/$',logins),
    url(r'^index/$', index),
    url(r'^add_user/$',add_user),
    url(r'^display_user/$',display_user),
    url(r'^del_user/$',del_user),
    url(r'^display_this_user/$',display_this_user),
    url(r'^update_user/$',update_user),


    url(r'^add_project/$',add_project),
    url(r'^del_project/$',del_project),
    url(r'^update_project/$',update_project),
    url(r'^display_project/$',display_project),
    url(r'^display_this_project/$',display_this_project),
    #url(r'^admin/$',admin),


    url(r'^add_work_content/$',add_work_content),
    url(r'^display_work_content/$',display_work_content),
    url(r'^update_work_content/$',update_work_content),
    url(r'^del_work_content/$',del_work_content),
    url(r'^display_all_work_content/$',display_all_work_content),####
    url(r'^display_all_work_content_query/$',display_all_work_content_query),
    url(r'^select_option/$',select_option),
    url(r'^upload_info/$',upload_info),
    url(r'^get_info/$',get_info),
    # url(r'^xx/$',xx),
    url(r'^select_option_flag/$',select_option_flag),
    url(r'^change_flag/$',change_flag),
    url(r'^change_flag_1/$',change_flag_1),
    url(r'^change_flag_3/$',change_flag_3),
    url(r'^upload_project/$',upload_project),
    url(r'^del_work_content_more/$',del_work_content_more),
    url(r'^frozen_user/$',frozen_user),
    url(r'^select_option_flag_person/$',select_option_flag_person),
    url(r'^add_project_duty/$',add_project_duty),
    url(r'^display_duty/$',display_duty),
    url(r'^del_duty/$',del_duty),
    url(r'^add_saleman/$',add_saleman),
    url(r'^display_saleman/$',display_saleman),
    url(r'^del_saleman/$',del_saleman),
    url(r'^update_saleman/$',update_saleman),
    url(r'^update_client/$',update_client),
    url(r'^display_worktype/$',display_worktype),
    url(r'^add_worktype/$',add_worktype),
    url(r'^del_worktype/$',del_worktype),
    url(r'^update_worktype/$',update_worktype),
    url(r'^show_work_count/$',show_work_count),
    url(r'^show_work_count_month/$',show_work_count_month),
    url(r'^updateTrack/$',updateTrack),
    url(r'^updateTrack_remark/$',updateTrack_remark),
    url(r'^get_server_date/$',get_server_date),
    url(r'^duty_updateTrack_AND_add_pro_report/$',duty_updateTrack_AND_add_pro_report),
    url(r'^display_project_report/$',display_project_report),
    url(r'^del_project_report/$',del_project_report),
    url(r'^select_last_pro_update/$',select_last_pro_update),
    url(r'^select_last_pro_report/$',select_last_pro_report),
    url(r'^sort_prj_contentdata/$',sort_prj_contentdata),
    url(r'^sort_report_serial_number/$',sort_report_serial_number),
    url(r'^upload_contract/$',upload_contract),
    url(r'^upload_contract1/$',upload_contract1),
    url(r'^change_cont_status_OK/$',change_cont_status_OK),
    url(r'^change_cont_status_None/$',change_cont_status_None),
    url(r'^download_ht/$',download_ht),
    url(r'^get_workinfo/$',get_workinfo),
    url(r'^addAchive/$',addAchive),
    url(r'^display_archive/$',display_archive),
    url(r'^upload_achive_tmp/$',upload_achive_tmp),
    url(r'^delete_tmp_achive/$',delete_tmp_achive),
    url(r'^delete_tmp_achive_old/$',delete_tmp_achive_old),
    url(r'^delete_tmp_all/$',delete_tmp_all),
    url(r'^select_archive_id/$',select_archive_id),
    url(r'^changeAchive/$',changeAchive),
    url(r'^delete_achive_jilu/$',delete_achive_jilu),
    url(r'^select_archive/$',select_archive),
    url(r'^add_tmp_achive_old/$',add_tmp_achive_old),
    url(r'^check_archive_item/$',check_archive_item),
    url(r'^check_archive_item_cy/$',check_archive_item_cy),
    url(r'^sort_clientname/$',sort_clientname),
    url(r'^get_equipment/$',get_equipment),
    url(r'^add_equipment/$',add_equipment),
    url(r'^change_equipment/$',change_equipment),
    url(r'^display_equipment/$',display_equipment),
    url(r'^check_equipment_item/$',check_equipment_item),
    url(r'^del_cont_equipment/$',del_cont_equipment),
    url(r'^display_cont_equip/$',display_cont_equip),
    url(r'^updata_change_equipment/$',updata_change_equipment),
    url(r'^updata_add_equipment/$',updata_add_equipment),
    url(r'^chooseinfo_equipment_item/$',chooseinfo_equipment_item),
    url(r'^display_equip_meta/$',display_equip_meta),
    url(r'^update_equip_meta/$',update_equip_meta),
    url(r'^add_equip_meta/$',add_equip_meta),
    url(r'^del_equip_meta/$',del_equip_meta),
    url(r'^select_equipment_meta/$',select_equipment_meta),
    url(r'^del_cont_equip/$',del_cont_equip),
    url(r'^check_equipment_serial/$',check_equipment_serial),
    url(r'^check_equipment_serial_list/$',check_equipment_serial_list),
    url(r'^upload_equpment/$',upload_equpment),
    url(r'^import_equipment_data_to_db/$',import_equipment_data_to_db),
    url(r'^delete_equipment_file_from_server/$',delete_equipment_file_from_server),
    url(r'^update_warranty_cont/$',update_warranty_cont),
    url(r'^add_personnel_input/$',add_personnel_input),
    url(r'^display_personnel_input/$',display_personnel_input),
    url(r'^update_personnel_input/$',update_personnel_input),
    url(r'^del_personnel_input/$',del_personnel_input),
    url(r'^display_cont_performance/$',display_cont_performance),
    url(r'^query_per_per/$',query_per_per),
    url(r'^search_personnel_input/$',search_personnel_input),
    # url(r'^delete_file/$',delete_file),
    url(r'^query_per_per/$',query_per_per),
    url(r'^upload_file_soft/$',upload_file_soft),
    url(r'^upload_file_soft_wdb/$',upload_file_soft_wdb),
    url(r'^select_share_file/$',select_share_file),
    url(r'^download_share_file/$',download_share_file),
    url(r'^paging_query_file/$',paging_query_file),
    url(r'^produce_page/$',produce_page),
    url(r'^produce_page_for_showAll/$',produce_page_for_showAll),
    url(r'^check_upload_filename_same/$',check_upload_filename_same),
    url(r'^get_update_tishi/$',get_update_tishi),

    
    
    
        
]
